/// Timing constants and environment wiring.
///
/// Development runs at 2-minute windows so the whole send -> wait -> open ->
/// fade cycle is observable in a couple of minutes instead of a couple of days.
/// The Firestore rules have a matching dev variant (firestore.dev.rules,
/// generated by tools/make_dev_rules.mjs) — change one and you MUST regenerate
/// the other, or writes start failing with opaque permission errors.
///
///   flutter run --dart-define=TIDAL_ENV=prod
class Config {
  const Config._();

  static const env = String.fromEnvironment('TIDAL_ENV', defaultValue: 'dev');
  static bool get isDev => env != 'prod';

  /// How long an opened letter stays readable.
  static Duration get openTtl =>
      isDev ? const Duration(minutes: 2) : const Duration(hours: 16);

  /// Minimum gap between letters from the same sender.
  static Duration get sendCooldown =>
      isDev ? const Duration(minutes: 2) : const Duration(hours: 8);

  /// How long the cat stays awake showing an opened letter before going back
  /// to sleep. The letter itself stays readable in the journal until its real
  /// 16h expiry — this only governs the awake display.
  static Duration get readingWindow =>
      isDev ? const Duration(seconds: 60) : const Duration(minutes: 10);

  /// Sentinel lifetime for a letter that is never opened. Exists only so the
  /// TTL field is never null (Firestore allows one TTL field per collection
  /// group, and a null one would leave abandoned docs immortal).
  static Duration get unopenedTtl =>
      isDev ? const Duration(hours: 24) : const Duration(days: 90);

  /// Point the SDK at local emulators instead of the real project.
  ///   flutter run --dart-define=USE_EMULATOR=true
  static const useEmulator =
      bool.fromEnvironment('USE_EMULATOR', defaultValue: false);
  static const emulatorHost =
      String.fromEnvironment('EMULATOR_HOST', defaultValue: '127.0.0.1');
  static const firestoreEmulatorPort = 8089;
  static const authEmulatorPort = 9099;
}
