// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv0W7cf4rswW5YSp--0aaary1U9JnXZWk',
    appId: '1:397624542945:android:3b7c2531f3feae1443d9a0',
    messagingSenderId: '397624542945',
    projectId: 'napcat-2e042',
    storageBucket: 'napcat-2e042.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPRpnlEld3mQ2XBbX4dgJy-qbesorDHw',
    appId: '1:397624542945:ios:ae44365c9810969843d9a0',
    messagingSenderId: '397624542945',
    projectId: 'napcat-2e042',
    storageBucket: 'napcat-2e042.firebasestorage.app',
    iosBundleId: 'com.mypeblo.tidal',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDprIax8MAD_kvdIR1Gl93GdyAHg_D5s',
    appId: '1:397624542945:web:12f6d2d1e7d5bbc043d9a0',
    messagingSenderId: '397624542945',
    projectId: 'napcat-2e042',
    authDomain: 'napcat-2e042.firebaseapp.com',
    storageBucket: 'napcat-2e042.firebasestorage.app',
    measurementId: 'G-P46FSR0Z92',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPRpnlEld3mQ2XBbX4dgJy-qbesorDHw',
    appId: '1:397624542945:ios:ad1cb45faea1264943d9a0',
    messagingSenderId: '397624542945',
    projectId: 'napcat-2e042',
    storageBucket: 'napcat-2e042.firebasestorage.app',
    iosBundleId: 'com.mypeblo.tidal.desktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpDprIax8MAD_kvdIR1Gl93GdyAHg_D5s',
    appId: '1:397624542945:web:bdf075da2475b3de43d9a0',
    messagingSenderId: '397624542945',
    projectId: 'napcat-2e042',
    authDomain: 'napcat-2e042.firebaseapp.com',
    storageBucket: 'napcat-2e042.firebasestorage.app',
    measurementId: 'G-5FFGJDMBCY',
  );
}
