// firestore.rules is the single source of truth. The dev variant differs ONLY in
// the four duration functions, so generate it instead of maintaining a copy.
// Run: node tools/make_dev_rules.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const DEV = {
  sendCooldown: "duration.value(2, 'm')",
  openTtl:      "duration.value(2, 'm')",
  unopenedMin:  "duration.value(23, 'h')",
  unopenedMax:  "duration.value(25, 'h')",
};

const src = readFileSync('firestore.rules', 'utf8');
let out = src;
for (const [fn, value] of Object.entries(DEV)) {
  const re = new RegExp(`(function ${fn}\\(\\)\\s*\\{ return )[^;]+(; \\})`);
  if (!re.test(out)) throw new Error(`could not find duration function: ${fn}`);
  out = out.replace(re, `$1${value}$2`);
}
if (out === src) throw new Error('no substitutions made — check firestore.rules formatting');

writeFileSync('firestore.dev.rules',
  '// GENERATED by tools/make_dev_rules.mjs from firestore.rules — do not edit.\n' +
  '// Short durations for development. Regenerate after any rules change.\n' + out);
console.log('wrote firestore.dev.rules');
